# Generated by Django 4.2.9 on 2024-09-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0014_adddoublecreative_date_doublestickercreative_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsinglecreative',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл для креатива'),
        ),
    ]
